- title: Subscriptions
  id: subscriptions
  feedSources:
    - id: inv_auth_feed
      title: Subscriptions
      apiType: Invidious
      endpoint: auth_feed

- title: Trending
  id: trending
  feedSources:
    - id: inv_trending
      title: Trending
      apiType: Invidious
      endpoint: trending

- title: Trending - Music
  id: trending_music
  feedSources:
    - id: inv_trending_music
      title: Trending - Music
      apiType: Invidious
      endpoint: trending
      queryParams:
        type: Music

- title: Trending - Gaming
  id: trending_gaming
  feedSources:
    - id: inv_trending_gaming
      title: Trending - Gaming
      apiType: Invidious
      endpoint: trending
      queryParams:
        type: Gaming

- title: Trending - Movies
  id: trending_movies
  feedSources:
    - id: inv_trending_movies
      title: Trending - Movies
      apiType: Invidious
      endpoint: trending
      queryParams:
        type: Movies

- title: Popular
  id: popular
  feedSources:
    - id: inv_popular
      title: Popular
      apiType: Invidious
      endpoint: popular

- title: Playlists
  id: playlists
  feedSources:
    - id: inv_auth_playlists
      title: Playlists
      apiType: Invidious
      endpoint: auth_playlists

- title: Watch history
  id: watch_history
  feedSources:
    - id: inv_auth_history
      title: Watch history
      apiType: Invidious
      endpoint: watch_history

- title: Channels
  id: channels
  feedSources:
    - id: inv_auth_channels
      title: Channels
      apiType: Invidious
      endpoint: auth_channels
