- title: Continue watching
  id: continue_watching
  reactivity:
    - node: /ContinueWatching
      field: changed
  feedSources:
    - id: local_continue_watching
      title: Continue watching
      apiType: Local
      endpoint: continue_watching

- title: Subscriptions
  id: subscriptions
  reactivity:
    - node: /Invidious
      field: authToken
  feedSources:
    - id: inv_auth_feed
      title: Subscriptions
      apiType: Invidious
      endpoint: auth_feed

- title: Trending
  id: trending
  feedSources:
    - id: inv_trending
      title: Trending
      apiType: Invidious
      endpoint: trending

- title: Trending - Music
  id: trending_music
  feedSources:
    - id: inv_trending_music
      title: Trending - Music
      apiType: Invidious
      endpoint: trending
      queryParams:
        type: Music

- title: Trending - Gaming
  id: trending_gaming
  feedSources:
    - id: inv_trending_gaming
      title: Trending - Gaming
      apiType: Invidious
      endpoint: trending
      queryParams:
        type: Gaming

- title: Trending - Movies
  id: trending_movies
  feedSources:
    - id: inv_trending_movies
      title: Trending - Movies
      apiType: Invidious
      endpoint: trending
      queryParams:
        type: Movies

- title: Popular
  id: popular
  feedSources:
    - id: inv_popular
      title: Popular
      apiType: Invidious
      endpoint: popular

- title: Playlists
  id: playlists
  reactivity:
    - node: /Invidious
      field: authToken
  feedSources:
    - id: inv_auth_playlists
      title: Playlists
      apiType: Invidious
      endpoint: auth_playlists

- title: Watch history
  id: watch_history
  reactivity:
    - node: /Invidious
      field: authToken
  feedSources:
    - id: local_watch_history
      title: Watch history
      apiType: Local
      endpoint: watch_history
