- title: Subscriptions
  id: subscriptions
  feedSources:
    - id: inv_auth_feed
      title: Subscriptions
      apiType: Invidious
      endpoint: auth_feed

- title: Recommended
  id: recommended
  feedSources:
    - id: inv_auth_recommended
      title: Recommended
      apiType: Invidious
      endpoint: auth_recommended

- title: Popular
  id: popular
  feedSources:
    - id: inv_popular
      title: Popular
      apiType: Invidious
      endpoint: popular

- title: Playlists
  id: playlists
  feedSources:
    - id: inv_auth_playlists
      title: Playlists
      apiType: Invidious
      endpoint: auth_playlists

- title: Watch history
  id: watch_history
  feedSources:
    - id: inv_auth_history
      title: Watch history
      apiType: Invidious
      endpoint: watch_history
